name = "Tea Pot"
provider_name = "airflow-provider-tea-pot"
provider_slug = "airflow_provider_tea_pot"
airflow_version = "2.3.4"
github_namespace = "username_or_org"
author_name = "Osborne Reynolds"
author_email = "osborne.reynolds@airflow.com"
short_description = "A provider for something short and stout."
