name = "Tea Pot"
provider_name = "airflow-provider-tea-pot"
provider_slug = "airflow_provider_tea_pot"
airflow_version = "2.5.0"
author_name = "Osborne Reynolds"
author_email = "osborne.reynolds@airflow.com"
short_description = "Short and stout."
